### PR TITLE
Create index.html maynewayent.com

### PR DESCRIPTION
**Pull request by LahyanDjeh**

### CODE REVIEW

**Comment by oalders** [comment]
Spam

**Comment by ioncache** [comment]
Bah, they could have at least added content to that file!  so boring with just the file name

**Comment by oalders** [comment]
Good to hear from you, @ioncache!

**Comment by ioncache** [comment]
> 
> 
> Good to hear from you, @ioncache!

Yeah it's been a while!

I still occasionally look at the metacpan issues/prs just to see what's going on =)

Been a really long time since I did any perl at this point though.  Not sure I understand it now 😉 

Hope things are going well with you @oalders

**Comment by oalders** [comment]
Things are good over here, thanks! If you ever want to present something to TPM, I'm guessing you'd have some interesting material based on your current $work. 😃

**Comment by ioncache** [comment]
> 
> 
> Things are good over here, thanks! If you ever want to present something to TPM, I'm guessing you'd have some interesting material based on your current $work. 😃

Hmm I'll have to think about that.  As long as you all could stand to see some java script that is hehe

**Comment by oalders** [comment]
That would be great! We even spent an evening trying to convert the TPM website to Hugo (we never finished), so it doesn't have to be about Perl at all.

**Pull request closed without merging**
